#!/bin/bash

# selected GRAILS environment values include:  development (locahost), matisse, dunkel, production, standalone_production
# see grails-app/conf/application.yml

GRAILS_ENV=production

CMD=assemble
DO_IT=true

while [ $1 ] ; do
	case $1 in
		"show" ) 
			VISIBLE=true
			GRAILS_ENV=standalone_production
			;;
		"war" ) CMD=war;;
		"-x" ) unset DO_IT;;
		*) GRAILS_ENV=$1;;
	esac
	shift
done

# if [ $1 ] ; then
#	if [ $1 = "show" ] ; then
#		VISIBLE=true
#	else
#		GRAILS_ENV=$1
#	fi
#	shift
#fi
#if [ $1 ] ; then
#	if [ $1 = "show" ] ; then
#		VISIBLE=true
#	else
#		GRAILS_ENV=$1
#	fi
#fi

backup=.sed-backup
uidoc=gwt/gov/noaa/pmel/sdig/client/DashboardLayout.ui.xml

if [ $VISIBLE ] ; then
	echo "setting nav bars to visible"
	sed -i ${backup}_1  's/<b:Navbar visible="false"/<b:Navbar visible="true"/' $uidoc
	sed -i ${backup}_1.2  's/addStyleNames="{style.footerHidden}"/addStyleNames="{style.footerVisible}"/' $uidoc
	SHOW=".show"
else 
	echo "setting nav bars back to noshow just in case"
	sed -i ${backup}_2 's/<b:Navbar visible="true"/<b:Navbar visible="false"/' $uidoc
	sed -i ${backup}_2.2  's/addStyleNames="{style.footerVisible}"/addStyleNames="{style.footerHidden}"/' $uidoc
fi

echo "Building Metadata Editor as $CMD for environment $GRAILS_ENV"
if [ $DO_IT ] ; then
	\rm build/libs/env.* 2&> /dev/null
	./gradlew -Dgrails.env=$GRAILS_ENV clean $CMD
else
	echo "BUILD CANCELLED"
fi

if [ $VISIBLE ] ; then
	echo "setting nav bars back to noshow"
	sed -i ${backup}_2 's/<b:Navbar visible="true"/<b:Navbar visible="false"/' $uidoc
	sed -i ${backup}_2.2  's/addStyleNames="{style.footerVisible}"/addStyleNames="{style.footerHidden}"/' $uidoc
fi

touch build/libs/env.${GRAILS_ENV}.${CMD}${SHOW}

