#!/bin/sh
APPDIR=`dirname $0`
GWTDIR="/usr/local/gwt-2.8.0"
LIBS=./lib/*
CLASSPATH="${LIBS}:${GWTDIR}/*:${APPDIR}/gwt"
CMPNTDIR="./src/main/webapp"
JAVAOPS="-Xmx1024M -Xms1024M"
GWTOPTIONS="-strict"

echo java ${JAVAOPS} -cp "${CLASSPATH}" com.google.gwt.dev.Compiler -war "${CMPNTDIR}" "$@" ${GWTOPTIONS} climatedatacloud.hrrr.Map
java ${JAVAOPS} -cp "${CLASSPATH}" com.google.gwt.dev.Compiler -style DETAILED -war "${CMPNTDIR}" "$@" ${GWTOPTIONS} gov.noaa.pmel.sdig.OAPMetadataEditor
