#!/bin/sh
APPDIR=`dirname $0`
GWTDIR="/Users/kamb/libs/gwt/gwt-2.8.2"
LIBS=./lib/*
CLASSPATH="${LIBS}:${GWTDIR}/*:${APPDIR}/gwt"
#CLASSPATH="${LIBS}:${APPDIR}/gwt"
CMPNTDIR="./src/main/webapp"
JAVAOPS="-Xmx1024M -Xms1024M"
COMPILE_REPORT="-compileReport"
GWTOPTIONS="-strict $COMPILE_REPORT"
OPTIMIZE="-optimize 9"
# STYLE="-style DETAILED"
MODULE=gov.noaa.pmel.sdig.OAPMetadataEditor

echo java ${JAVAOPS} -cp "${CLASSPATH}" com.google.gwt.dev.Compiler ${STYLE} ${OPTIMIZE} -war "${CMPNTDIR}" "$@" ${GWTOPTIONS} $MODULE
java ${JAVAOPS} -cp "${CLASSPATH}" com.google.gwt.dev.Compiler ${STYLE} ${OPTIMIZE} -war "${CMPNTDIR}" "$@" ${GWTOPTIONS} $MODULE
