package gov.noaa.pmel.sdig.shared.bean.list;

import java.util.ArrayList;

/**
 * Created by rhs on 5/31/17.
 */
public class SuggestedVariables extends ArrayList<String> {
    public SuggestedVariables() {
        add("Earth Science > Atmosphere > Atmospheric Temperature > Surface Temperature > Dew Point Temperature > Dewpoint Depression");
        add("Earth Science > Atmosphere > Atmospheric Temperature > Surface Temperature > Maximum/Minimum Temperature > 24 Hour Maximum Temperature");
        add("Earth Science > Atmosphere > Atmospheric Temperature > Surface Temperature > Maximum/Minimum Temperature > 24 Hour Minimum Temperature");
        add("Earth Science > Atmosphere > Atmospheric Temperature > Surface Temperature > Maximum/Minimum Temperature > 6 Hour Maximum Temperature");
        add("Earth Science > Atmosphere > Atmospheric Temperature > Surface Temperature > Maximum/Minimum Temperature > 6 Hour Minimum Temperature");
        add("Earth Science > Atmosphere > Atmospheric Temperature > Upper Air Temperature > Dew Point Temperature > Dew Point Depression");
        add("Earth Science > Atmosphere > Atmospheric Temperature > Upper Air Temperature > Vertical Profiles > Dry Adiabatic Lapse Rate");
        add("Earth Science > Atmosphere > Atmospheric Temperature > Upper Air Temperature > Vertical Profiles > Environmental Lapse Rate");
        add("Earth Science > Atmosphere > Atmospheric Temperature > Upper Air Temperature > Vertical Profiles > Inversion Height");
        add("Earth Science > Atmosphere > Atmospheric Temperature > Upper Air Temperature > Vertical Profiles > Saturated Adiabatic Lapse Rate");
        add("Earth Science > Atmosphere > Atmospheric Water Vapor > Water Vapor Indicators > Humidity > Absolute Humidity");
        add("Earth Science > Atmosphere > Atmospheric Water Vapor > Water Vapor Indicators > Humidity > Humidity Mixing Ratio");
        add("Earth Science > Atmosphere > Atmospheric Water Vapor > Water Vapor Indicators > Humidity > Relative Humidity");
        add("Earth Science > Atmosphere > Atmospheric Water Vapor > Water Vapor Indicators > Humidity > Saturation Specific Humidity");
        add("Earth Science > Atmosphere > Atmospheric Water Vapor > Water Vapor Indicators > Humidity > Specific Humidity");
        add("Earth Science > Atmosphere > Atmospheric Water Vapor > Water Vapor Processes > Evapotranspiration > Effective Evapotranspiration");
        add("Earth Science > Atmosphere > Atmospheric Water Vapor > Water Vapor Processes > Evapotranspiration > Potential Evapotranspiration");
        add("Earth Science > Atmosphere > Atmospheric Winds > Local Winds > Orographic Winds > Anabatic Winds");
        add("Earth Science > Atmosphere > Atmospheric Winds > Local Winds > Orographic Winds > Bora Winds");
        add("Earth Science > Atmosphere > Atmospheric Winds > Local Winds > Orographic Winds > Foehn Winds");
        add("Earth Science > Atmosphere > Atmospheric Winds > Local Winds > Orographic Winds > Katabatic Winds");
        add("Earth Science > Atmosphere > Atmospheric Winds > Local Winds > Orographic Winds > Mountain Breezes");
        add("Earth Science > Atmosphere > Atmospheric Winds > Local Winds > Orographic Winds > Valley Breezes");
        add("Earth Science > Atmosphere > Atmospheric Winds > Wind Dynamics > Vorticity > Potential Vorticity");
        add("Earth Science > Atmosphere > Atmospheric Winds > Wind Dynamics > Vorticity > Vorticity Advection");
        add("Earth Science > Atmosphere > Atmospheric Winds > Wind Dynamics > Wind Shear > Horizontal Wind Shear");
        add("Earth Science > Atmosphere > Atmospheric Winds > Wind Dynamics > Wind Shear > Vertical Wind Shear");
        add("Earth Science > Atmosphere > Clouds > Cloud Dynamics > Moisture Flux > Downward Moisture Flux");
        add("Earth Science > Atmosphere > Clouds > Cloud Dynamics > Moisture Flux > Upward Moisture Flux");
        add("Earth Science > Atmosphere > Clouds > Cloud Dynamics > Vortex Street > Karman Vortex Street");
        add("Earth Science > Atmosphere > Clouds > Cloud Microphysics > Droplet Growth > Accretion");
        add("Earth Science > Atmosphere > Clouds > Cloud Microphysics > Droplet Growth > Accretion");
        add("Earth Science > Atmosphere > Clouds > Cloud Microphysics > Droplet Growth > Aggregation");
        add("Earth Science > Atmosphere > Clouds > Cloud Microphysics > Droplet Growth > Coalescence");
        add("Earth Science > Atmosphere > Clouds > Cloud Microphysics > Sedimentation > Sedimentation Rate");
        add("Earth Science > Atmosphere > Clouds > Convective Clouds/Systems (Observed/Analyzed) > Cumulonimbus > Cumulonimbus Calvus");
        add("Earth Science > Atmosphere > Clouds > Convective Clouds/Systems (Observed/Analyzed) > Cumulonimbus > Cumulonimbus Capillatus");
        add("Earth Science > Atmosphere > Clouds > Convective Clouds/Systems (Observed/Analyzed) > Cumulonimbus > Cumulonimbus Capillatus");
        add("Earth Science > Atmosphere > Clouds > Convective Clouds/Systems (Observed/Analyzed) > Cumulonimbus > Pyrocumulonimbus");
        add("Earth Science > Atmosphere > Clouds > Convective Clouds/Systems (Observed/Analyzed) > Cumulus > Cumulus Castellanus");
        add("Earth Science > Atmosphere > Clouds > Convective Clouds/Systems (Observed/Analyzed) > Cumulus > Cumulus Congestus");
        add("Earth Science > Atmosphere > Clouds > Convective Clouds/Systems (Observed/Analyzed) > Cumulus > Cumulus Congestus");
        add("Earth Science > Atmosphere > Clouds > Convective Clouds/Systems (Observed/Analyzed) > Cumulus > Cumulus Humilis");
        add("Earth Science > Atmosphere > Clouds > Convective Clouds/Systems (Observed/Analyzed) > Cumulus > Cumulus Humilis");
        add("Earth Science > Atmosphere > Clouds > Convective Clouds/Systems (Observed/Analyzed) > Cumulus > Cumulus Mediocris");
        add("Earth Science > Atmosphere > Clouds > Convective Clouds/Systems (Observed/Analyzed) > Cumulus > Pyrocumulus");
        add("Earth Science > Atmosphere > Clouds > Tropospheric/High-Level Clouds (Observed/Analyzed) > Cirrus/Systems > Cirrus Cloud Systems");
        add("Earth Science > Atmosphere > Clouds > Tropospheric/High-Level Clouds (Observed/Analyzed) > Cirrus/Systems > Cirrus Kelvin-Helmholtz Colombiah");
        add("Earth Science > Atmosphere > Clouds > Tropospheric/Low Level Clouds (Observed/Analyzed) > Fog > Advection Fog");
        add("Earth Science > Atmosphere > Clouds > Tropospheric/Low Level Clouds (Observed/Analyzed) > Fog > Frontal Fog");
        add("Earth Science > Atmosphere > Clouds > Tropospheric/Low Level Clouds (Observed/Analyzed) > Fog > Ice Fog");
        add("Earth Science > Atmosphere > Clouds > Tropospheric/Low Level Clouds (Observed/Analyzed) > Fog > Radiation Fog");
        add("Earth Science > Atmosphere > Clouds > Tropospheric/Low Level Clouds (Observed/Analyzed) > Fog > Steam Fog");
        add("Earth Science > Atmosphere > Clouds > Tropospheric/Low Level Clouds (Observed/Analyzed) > Fog > Upslope Fog");
        add("Earth Science > Atmosphere > Clouds > Tropospheric/Low Level Clouds (Observed/Analyzed) > Stratocumulus > Marine Stratocumulus");
        add("Earth Science > Atmosphere > Clouds > Tropospheric/Low Level Clouds (Observed/Analyzed) > Stratocumulus > Stratocumulus Cumiliformis");
        add("Earth Science > Atmosphere > Clouds > Tropospheric/Low Level Clouds (Observed/Analyzed) > Stratocumulus > Stratocumulus Cumiliformis");
        add("Earth Science > Atmosphere > Clouds > Tropospheric/Low Level Clouds (Observed/Analyzed) > Stratocumulus > Stratocumulus Cumiliformis");
        add("Earth Science > Atmosphere > Clouds > Tropospheric/Low Level Clouds (Observed/Analyzed) > Stratocumulus > Stratocumulus Cumiliformis");
        add("Earth Science > Atmosphere > Clouds > Tropospheric/Low Level Clouds (Observed/Analyzed) > Stratocumulus > Stratocumulus Cumiliformis");
        add("Earth Science > Atmosphere > Clouds > Tropospheric/Low Level Clouds (Observed/Analyzed) > Stratocumulus > Stratocumulus Undulatas");
        add("Earth Science > Atmosphere > Clouds > Tropospheric/Low Level Clouds (Observed/Analyzed) > Stratocumulus > Stratocumulus Undulatas");
        add("Earth Science > Atmosphere > Clouds > Tropospheric/Low Level Clouds (Observed/Analyzed) > Stratocumulus > Stratocumulus Undulatas");
        add("Earth Science > Atmosphere > Clouds > Tropospheric/Low Level Clouds (Observed/Analyzed) > Stratocumulus > Stratocumulus Undulatas");
        add("Earth Science > Atmosphere > Clouds > Tropospheric/Low Level Clouds (Observed/Analyzed) > Stratocumulus > Stratocumulus Undulatas");
        add("Earth Science > Atmosphere > Clouds > Tropospheric/Mid-Level Clouds (Observed/Analyzed) > Altocumulus > Altocumulus Castellanus");
        add("Earth Science > Atmosphere > Clouds > Tropospheric/Mid-Level Clouds (Observed/Analyzed) > Altocumulus > Altocumulus Lenticularis");
        add("Earth Science > Atmosphere > Clouds > Tropospheric/Mid-Level Clouds (Observed/Analyzed) > Altocumulus > Altocumulus Lenticularis");
        add("Earth Science > Atmosphere > Clouds > Tropospheric/Mid-Level Clouds (Observed/Analyzed) > Altocumulus > Altocumulus Undulatus");
        add("Earth Science > Atmosphere > Clouds > Tropospheric/Mid-Level Clouds (Observed/Analyzed) > Altostratus > Altostratus Undulatus");
        add("Earth Science > Atmosphere > Precipitation > Liquid Precipitation > Drizzle > Freezing Drizzle");
        add("Earth Science > Atmosphere > Precipitation > Liquid Precipitation > Rain > Acid Rain");
        add("Earth Science > Atmosphere > Precipitation > Liquid Precipitation > Rain > Freezing Rain");
        add("Earth Science > Atmosphere > Precipitation > Solid Precipitation > Ice Pellets > Sleet");
        add("Earth Science > Atmosphere > Precipitation > Solid Precipitation > Ice Pellets > Small Hail");
        add("Earth Science > Atmosphere > Precipitation > Solid Precipitation > Snow > Snow Grains");
        add("Earth Science > Atmosphere > Precipitation > Solid Precipitation > Snow > Snow Pellets");
        add("Earth Science > Atmosphere > Weather Events > Subtropical Cyclones > Subtropical Depression > Subtropical Depression Track");
        add("Earth Science > Atmosphere > Weather Events > Subtropical Cyclones > Subtropical Storm > Subtropical Storm Motion");
        add("Earth Science > Atmosphere > Weather Events > Subtropical Cyclones > Subtropical Storm > Subtropical Storm Track");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Accumulated Cyclone Energy > Cyclones (Sw Indian)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Accumulated Cyclone Energy > Hurricanes  (N. Atlantic/E. Pacific)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Accumulated Cyclone Energy > Severe Cyclonic Storms (N. Indian)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Accumulated Cyclone Energy > Severe Tropical Cyclones (Sw Pacific/Se Indian)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Accumulated Cyclone Energy > Typhoons (Western N. Pacific)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Landfall Intensity > Cyclones (Sw Indian)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Landfall Intensity > Hurricanes  (N. Atlantic/E. Pacific)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Landfall Intensity > Severe Cyclonic Storms (N. Indian)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Landfall Intensity > Severe Tropical Cyclones (Sw Pacific/Se Indian)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Landfall Intensity > Typhoons (Western N. Pacific)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Maximum 1-Minute Sustained Wind > Cyclones (Sw Indian)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Maximum 1-Minute Sustained Wind > Hurricanes  (N. Atlantic/E. Pacific)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Maximum 1-Minute Sustained Wind > Severe Cyclonic Storms (N. Indian)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Maximum 1-Minute Sustained Wind > Severe Tropical Cyclones (Sw Pacific/Se Indian)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Maximum 1-Minute Sustained Wind > Typhoons (Western N. Pacific)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Maximum Surface Wind > Cyclones (Sw Indian)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Maximum Surface Wind > Hurricanes  (N. Atlantic/E. Pacific)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Maximum Surface Wind > Severe Cyclonic Storms (N. Indian)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Maximum Surface Wind > Severe Tropical Cyclones (Sw Pacific/Se Indian)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Maximum Surface Wind > Typhoons (Western N. Pacific)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Maximum Wind Gust > Cyclones (Sw Indian)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Maximum Wind Gust > Hurricanes  (N. Atlantic/E. Pacific)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Maximum Wind Gust > Severe Cyclonic Storms (N. Indian)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Maximum Wind Gust > Severe Tropical Cyclones (Sw Pacific/Se Indian)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Maximum Wind Gust > Typhoons (Western N. Pacific)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Minimum Central Pressure > Cyclones (Sw Indian)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Minimum Central Pressure > Hurricanes  (N. Atlantic/E. Pacific)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Minimum Central Pressure > Severe Cyclonic Storms (N. Indian)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Minimum Central Pressure > Severe Tropical Cyclones (Sw Pacific/Se Indian)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Minimum Central Pressure > Typhoons (Western N. Pacific)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Peak Intensity > Cyclones (Sw Indian)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Peak Intensity > Hurricanes  (N. Atlantic/E. Pacific)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Peak Intensity > Severe Cyclonic Storms (N. Indian)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Peak Intensity > Severe Tropical Cyclones (Sw Pacific/Se Indian)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Peak Intensity > Typhoons (Western N. Pacific)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Saffir-Simpson Scale At Landfall (Category 1) > Hurricanes  (N. Atlantic/E. Pacific)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Saffir-Simpson Scale At Landfall (Category 2) > Hurricanes  (N. Atlantic/E. Pacific)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Saffir-Simpson Scale At Landfall (Category 3) > Hurricanes  (N. Atlantic/E. Pacific)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Saffir-Simpson Scale At Landfall (Category 4) > Hurricanes  (N. Atlantic/E. Pacific)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Saffir-Simpson Scale At Landfall (Category 5) > Hurricanes  (N. Atlantic/E. Pacific)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Tropical Cyclone Force Wind Extent > Cyclones (Sw Indian)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Tropical Cyclone Force Wind Extent > Hurricanes  (N. Atlantic/E. Pacific)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Tropical Cyclone Force Wind Extent > Severe Cyclonic Storms (N. Indian)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Tropical Cyclone Force Wind Extent > Severe Tropical Cyclones (Sw Pacific/Se Indian)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Tropical Cyclone Force Wind Extent > Typhoons (Western N. Pacific)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Tropical Cyclone Motion > Cyclones (Sw Indian)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Tropical Cyclone Motion > Hurricanes  (N. Atlantic/E. Pacific)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Tropical Cyclone Motion > Severe Cyclonic Storms (N. Indian)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Tropical Cyclone Motion > Severe Tropical Cyclones (Sw Pacific/Se Indian)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Tropical Cyclone Motion > Typhoons (Western N. Pacific)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Tropical Cyclone Radius > Cyclones (Sw Indian)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Tropical Cyclone Radius > Hurricanes  (N. Atlantic/E. Pacific)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Tropical Cyclone Radius > Severe Cyclonic Storms (N. Indian)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Tropical Cyclone Radius > Severe Tropical Cyclones (Sw Pacific/Se Indian)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Tropical Cyclone Radius > Typhoons (Western N. Pacific)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Tropical Cyclone Track > Cyclones (Sw Indian)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Tropical Cyclone Track > Hurricanes  (N. Atlantic/E. Pacific)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Tropical Cyclone Track > Severe Cyclonic Storms (N. Indian)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Tropical Cyclone Track > Severe Tropical Cyclones (Sw Pacific/Se Indian)");
        add("Earth Science > Atmosphere > Weather Events > Tropical Cyclones > Tropical Cyclone Track > Typhoons (Western N. Pacific)");
        add("Earth Science > Biological Classification > Animals/Invertebrates > Arthropods > Chelicerates > Arachnids");
        add("Earth Science > Biological Classification > Animals/Invertebrates > Arthropods > Crustaceans > Amphipods");
        add("Earth Science > Biological Classification > Animals/Invertebrates > Arthropods > Crustaceans > Barnacles");
        add("Earth Science > Biological Classification > Animals/Invertebrates > Arthropods > Crustaceans > Copepods");
        add("Earth Science > Biological Classification > Animals/Invertebrates > Arthropods > Crustaceans > Decapods");
        add("Earth Science > Biological Classification > Animals/Invertebrates > Arthropods > Crustaceans > Euphausiids (Krill)");
        add("Earth Science > Biological Classification > Animals/Invertebrates > Arthropods > Crustaceans > Isopods");
        add("Earth Science > Biological Classification > Animals/Invertebrates > Arthropods > Crustaceans > Mysids");
        add("Earth Science > Biological Classification > Animals/Invertebrates > Arthropods > Crustaceans > Ostracods");
        add("Earth Science > Biological Classification > Animals/Invertebrates > Arthropods > Hexapods > Entognatha");
        add("Earth Science > Biological Classification > Animals/Invertebrates > Arthropods > Hexapods > Insects");
        add("Earth Science > Biological Classification > Animals/Invertebrates > Arthropods > Myriapods > Centipedes");
        add("Earth Science > Biological Classification > Animals/Invertebrates > Arthropods > Myriapods > Millipedes");
        add("Earth Science > Biological Classification > Animals/Invertebrates > Cnidarians > Anthozoans/Hexacorals > Hard Or Stony Corals");
        add("Earth Science > Biological Classification > Animals/Invertebrates > Cnidarians > Anthozoans/Hexacorals > Sea Anemones");
        add("Earth Science > Biological Classification > Animals/Invertebrates > Cnidarians > Anthozoans/Octocorals > Sea Fans/Sea Whips");
        add("Earth Science > Biological Classification > Animals/Invertebrates > Cnidarians > Anthozoans/Octocorals > Sea Pens");
        add("Earth Science > Biological Classification > Animals/Invertebrates > Cnidarians > Anthozoans/Octocorals > Soft Corals");
        add("Earth Science > Biological Classification > Animals/Invertebrates > Mollusks > Bivalves > Clams");
        add("Earth Science > Biological Classification > Animals/Invertebrates > Mollusks > Bivalves > Mussels");
        add("Earth Science > Biological Classification > Animals/Invertebrates > Mollusks > Bivalves > Oysters");
        add("Earth Science > Biological Classification > Animals/Invertebrates > Mollusks > Cephalopods > Squids");
        add("Earth Science > Biological Classification > Animals/Vertebrates > Fish > Ray-Finned Fishes > Anchovies/Herrings");
        add("Earth Science > Biological Classification > Animals/Vertebrates > Fish > Ray-Finned Fishes > Catfishes/Minnows");
        add("Earth Science > Biological Classification > Animals/Vertebrates > Fish > Ray-Finned Fishes > Cods/Haddocks");
        add("Earth Science > Biological Classification > Animals/Vertebrates > Fish > Ray-Finned Fishes > Flounders");
        add("Earth Science > Biological Classification > Animals/Vertebrates > Fish > Ray-Finned Fishes > Needlefishes");
        add("Earth Science > Biological Classification > Animals/Vertebrates > Fish > Ray-Finned Fishes > Perch-Like Fishes");
        add("Earth Science > Biological Classification > Animals/Vertebrates > Fish > Ray-Finned Fishes > Perch-Like Fishes");
        add("Earth Science > Biological Classification > Animals/Vertebrates > Fish > Ray-Finned Fishes > Pupfishes");
        add("Earth Science > Biological Classification > Animals/Vertebrates > Fish > Ray-Finned Fishes > Salmons/Trouts");
        add("Earth Science > Biological Classification > Animals/Vertebrates > Fish > Ray-Finned Fishes > Sturgeons/Paddlefishes");
        add("Earth Science > Biological Classification > Animals/Vertebrates > Mammals > Carnivores > Bears");
        add("Earth Science > Biological Classification > Animals/Vertebrates > Mammals > Carnivores > Dogs/Foxes/Wolves");
        add("Earth Science > Biological Classification > Animals/Vertebrates > Mammals > Carnivores > Martens/Weasels/Wolverines");
        add("Earth Science > Biological Classification > Animals/Vertebrates > Mammals > Carnivores > Otters");
        add("Earth Science > Biological Classification > Animals/Vertebrates > Mammals > Carnivores > Seals/Sea Lions/Walruses");
        add("Earth Science > Biological Classification > Animals/Vertebrates > Mammals > Cetaceans > Baleen Whales");
        add("Earth Science > Biological Classification > Animals/Vertebrates > Mammals > Cetaceans > Toothed Whales");
        add("Earth Science > Biological Classification > Animals/Vertebrates > Mammals > Even-Toed Ungulates > Cattle/Sheep");
        add("Earth Science > Biological Classification > Animals/Vertebrates > Mammals > Even-Toed Ungulates > Deer/Moose");
        add("Earth Science > Biological Classification > Animals/Vertebrates > Mammals > Even-Toed Ungulates > Hogs/Pigs");
        add("Earth Science > Biological Classification > Plants > Angiosperms (Flowering Plants) > Monocots > Seagrass");
        add("Earth Science > Biological Classification > Plants > Microalgae > Haptophytes > Coccolithophores");
        add("Earth Science > Biological Classification > Protists > Flagellates > Haptophytes > Coccolithophores");
        add("Earth Science > Biosphere > Ecosystems > Anthropogenic/Human Influenced Ecosystems > Agricultural Lands > Cropland");
        add("Earth Science > Biosphere > Ecosystems > Anthropogenic/Human Influenced Ecosystems > Agricultural Lands > Forest Plantation");
        add("Earth Science > Biosphere > Ecosystems > Anthropogenic/Human Influenced Ecosystems > Agricultural Lands > Pasture");
        add("Earth Science > Biosphere > Ecosystems > Anthropogenic/Human Influenced Ecosystems > Agricultural Lands > Rangeland");
        add("Earth Science > Biosphere > Ecosystems > Anthropogenic/Human Influenced Ecosystems > Resource Development Site > Minning/Drilling Site");
        add("Earth Science > Biosphere > Ecosystems > Anthropogenic/Human Influenced Ecosystems > Resource Development Site > Solar Farm");
        add("Earth Science > Biosphere > Ecosystems > Anthropogenic/Human Influenced Ecosystems > Resource Development Site > Water Impoundment");
        add("Earth Science > Biosphere > Ecosystems > Anthropogenic/Human Influenced Ecosystems > Resource Development Site > Wind Farm");
        add("Earth Science > Biosphere > Ecosystems > Anthropogenic/Human Influenced Ecosystems > Urban Lands > Canal");
        add("Earth Science > Biosphere > Ecosystems > Anthropogenic/Human Influenced Ecosystems > Urban Lands > Garden");
        add("Earth Science > Biosphere > Ecosystems > Anthropogenic/Human Influenced Ecosystems > Urban Lands > Park");
        add("Earth Science > Biosphere > Ecosystems > Anthropogenic/Human Influenced Ecosystems > Urban Lands > Roadside");
        add("Earth Science > Biosphere > Ecosystems > Aquatic Ecosystems > Plankton > Phytoplankton");
        add("Earth Science > Biosphere > Ecosystems > Aquatic Ecosystems > Plankton > Zooplankton");
        add("Earth Science > Biosphere > Ecosystems > Aquatic Ecosystems > Wetlands > Estuarine Wetlands");
        add("Earth Science > Biosphere > Ecosystems > Aquatic Ecosystems > Wetlands > Lacustrine Wetlands");
        add("Earth Science > Biosphere > Ecosystems > Aquatic Ecosystems > Wetlands > Marine");
        add("Earth Science > Biosphere > Ecosystems > Aquatic Ecosystems > Wetlands > Marshes");
        add("Earth Science > Biosphere > Ecosystems > Aquatic Ecosystems > Wetlands > Palustrine Wetlands");
        add("Earth Science > Biosphere > Ecosystems > Aquatic Ecosystems > Wetlands > Peatlands");
        add("Earth Science > Biosphere > Ecosystems > Aquatic Ecosystems > Wetlands > Riparian Wetlands");
        add("Earth Science > Biosphere > Ecosystems > Aquatic Ecosystems > Wetlands > Swamps");
        add("Earth Science > Biosphere > Ecosystems > Aquatic Ecosystems > Wetlands > Vernal Pool");
        add("Earth Science > Biosphere > Ecosystems > Freshwater Ecosystems > Lake/Pond > Montane Lake");
        add("Earth Science > Biosphere > Ecosystems > Freshwater Ecosystems > Lake/Pond > Saline Lakes");
        add("Earth Science > Biosphere > Ecosystems > Freshwater Ecosystems > Rivers/Stream > Ephemeral Stream");
        add("Earth Science > Biosphere > Ecosystems > Freshwater Ecosystems > Rivers/Stream > Headwater Stream");
        add("Earth Science > Biosphere > Ecosystems > Freshwater Ecosystems > Rivers/Stream > Intermittent Stream");
        add("Earth Science > Biosphere > Ecosystems > Freshwater Ecosystems > Rivers/Stream > Perennial Stream/River");
        add("Earth Science > Biosphere > Ecosystems > Freshwater Ecosystems > Rivers/Stream > River Delta");
        add("Earth Science > Biosphere > Ecosystems > Marine Ecosystems > Abyssal > Cold Seep");
        add("Earth Science > Biosphere > Ecosystems > Marine Ecosystems > Abyssal > Hydrothermal Vent");
        add("Earth Science > Biosphere > Ecosystems > Marine Ecosystems > Coastal > Beaches");
        add("Earth Science > Biosphere > Ecosystems > Marine Ecosystems > Coastal > Dunes");
        add("Earth Science > Biosphere > Ecosystems > Marine Ecosystems > Coastal > Kelp Forest");
        add("Earth Science > Biosphere > Ecosystems > Marine Ecosystems > Coastal > Lagoon");
        add("Earth Science > Biosphere > Ecosystems > Marine Ecosystems > Coastal > Mangrove Swamp");
        add("Earth Science > Biosphere > Ecosystems > Marine Ecosystems > Coastal > Mudflat");
        add("Earth Science > Biosphere > Ecosystems > Marine Ecosystems > Coastal > Rocky Intertidal");
        add("Earth Science > Biosphere > Ecosystems > Marine Ecosystems > Coastal > Salt Marsh");
        add("Earth Science > Biosphere > Ecosystems > Marine Ecosystems > Coastal > Sav/Sea Grass Bed");
        add("Earth Science > Biosphere > Ecosystems > Marine Ecosystems > Estuary > Brackish Marsh");
        add("Earth Science > Biosphere > Ecosystems > Marine Ecosystems > Estuary > Mangrove Swamp");
        add("Earth Science > Biosphere > Ecosystems > Marine Ecosystems > Estuary > Mudflat");
        add("Earth Science > Biosphere > Ecosystems > Marine Ecosystems > Estuary > Sav/Sea Grass Bed");
        add("Earth Science > Biosphere > Ecosystems > Marine Ecosystems > Pelagic > Neritic Zone");
        add("Earth Science > Biosphere > Ecosystems > Marine Ecosystems > Pelagic > Oceanic Zone");
        add("Earth Science > Biosphere > Ecosystems > Marine Ecosystems > Reef > Coral Reef");
        add("Earth Science > Biosphere > Ecosystems > Marine Ecosystems > Reef > Oyster Reef");
        add("Earth Science > Biosphere > Ecosystems > Terrestrial Ecosystems > Alpine/Tundra > Alpine Tundra");
        add("Earth Science > Biosphere > Ecosystems > Terrestrial Ecosystems > Alpine/Tundra > Arctic Tundra");
        add("Earth Science > Biosphere > Ecosystems > Terrestrial Ecosystems > Alpine/Tundra > Subalpine");
        add("Earth Science > Biosphere > Ecosystems > Terrestrial Ecosystems > Deserts > Desert Scrub");
        add("Earth Science > Biosphere > Ecosystems > Terrestrial Ecosystems > Forests > Boreal Forest/Tiaga");
        add("Earth Science > Biosphere > Ecosystems > Terrestrial Ecosystems > Forests > Temperate Coniferous Forest");
        add("Earth Science > Biosphere > Ecosystems > Terrestrial Ecosystems > Forests > Temperate Deciduous Forest");
        add("Earth Science > Biosphere > Ecosystems > Terrestrial Ecosystems > Forests > Temperate Mixed Forest");
        add("Earth Science > Biosphere > Ecosystems > Terrestrial Ecosystems > Forests > Temperate Rainforest");
        add("Earth Science > Biosphere > Ecosystems > Terrestrial Ecosystems > Forests > Tropical Rainforest");
        add("Earth Science > Biosphere > Ecosystems > Terrestrial Ecosystems > Grasslands > Montane Grassland");
        add("Earth Science > Biosphere > Ecosystems > Terrestrial Ecosystems > Grasslands > Savanna");
        add("Earth Science > Biosphere > Ecosystems > Terrestrial Ecosystems > Shrubland/Scrub > Chaparral");
        add("Earth Science > Biosphere > Ecosystems > Terrestrial Ecosystems > Shrubland/Scrub > Montane Shrubland");
        add("Earth Science > Biosphere > Ecosystems > Terrestrial Ecosystems > Wetlands > Estuarine Wetlands");
        add("Earth Science > Biosphere > Ecosystems > Terrestrial Ecosystems > Wetlands > Lacustrine Wetlands");
        add("Earth Science > Biosphere > Ecosystems > Terrestrial Ecosystems > Wetlands > Marine");
        add("Earth Science > Biosphere > Ecosystems > Terrestrial Ecosystems > Wetlands > Marshes");
        add("Earth Science > Biosphere > Ecosystems > Terrestrial Ecosystems > Wetlands > Palustrine Wetlands");
        add("Earth Science > Biosphere > Ecosystems > Terrestrial Ecosystems > Wetlands > Peatlands");
        add("Earth Science > Biosphere > Ecosystems > Terrestrial Ecosystems > Wetlands > Riparian Wetlands");
        add("Earth Science > Biosphere > Ecosystems > Terrestrial Ecosystems > Wetlands > Swamps");
        add("Earth Science > Climate Indicators > Atmospheric/Ocean Indicators > Humidity Indices > Temperature-Humidity Index > Thi");
        add("Earth Science > Climate Indicators > Atmospheric/Ocean Indicators > Humidity Indices > Water Vapor Transport Index > Wtvi");
        add("Earth Science > Climate Indicators > Atmospheric/Ocean Indicators > Ocean Upwelling Indices > Ocean Coastal Upwelling Index > Cui");
        add("Earth Science > Climate Indicators > Atmospheric/Ocean Indicators > Sea Surface Temperature Indices > Caribbean Index > Car");
        add("Earth Science > Climate Indicators > Atmospheric/Ocean Indicators > Sea Surface Temperature Indices > Central Tropical Pacific Sst > Nino 4 Index");
        add("Earth Science > Climate Indicators > Atmospheric/Ocean Indicators > Sea Surface Temperature Indices > East Central Tropical Pacific Sst > Nino 3.4 Index");
        add("Earth Science > Climate Indicators > Atmospheric/Ocean Indicators > Sea Surface Temperature Indices > Extreme Eastern Tropical Pacific Sst > Nino 1+2 Index");
        add("Earth Science > Climate Indicators > Atmospheric/Ocean Indicators > Sea Surface Temperature Indices > North Tropical Atlantic Index > Nta");
        add("Earth Science > Climate Indicators > Atmospheric/Ocean Indicators > Sea Surface Temperature Indices > Oceanic Nino Index > Oni");
        add("Earth Science > Climate Indicators > Atmospheric/Ocean Indicators > Sea Surface Temperature Indices > Trans-Nino Index > Tni");
        add("Earth Science > Climate Indicators > Atmospheric/Ocean Indicators > Sea Surface Temperature Indices > Tropical North Atlantic Index > Tna");
        add("Earth Science > Climate Indicators > Atmospheric/Ocean Indicators > Sea Surface Temperature Indices > Tropical South Atlantic Index > Tsa");
        add("Earth Science > Climate Indicators > Atmospheric/Ocean Indicators > Sea Surface Temperature Indices > Western Hemisphere Warm Pool > Whwp");
        add("Earth Science > Climate Indicators > Atmospheric/Ocean Indicators > Teleconnections > Antarctic Oscillation > Aao");
        add("Earth Science > Climate Indicators > Atmospheric/Ocean Indicators > Teleconnections > Arctic Oscillation > Ao");
        add("Earth Science > Climate Indicators > Atmospheric/Ocean Indicators > Teleconnections > Atlantic Meridional Mode > Amm");
        add("Earth Science > Climate Indicators > Atmospheric/Ocean Indicators > Teleconnections > Atlantic Multidecadal Oscillation Long Version > Amo");
        add("Earth Science > Climate Indicators > Atmospheric/Ocean Indicators > Teleconnections > Bivariate Enso Timeseries Index > Best");
        add("Earth Science > Climate Indicators > Atmospheric/Ocean Indicators > Teleconnections > East Atlantic Jet Pattern > Ea-Jet");
        add("Earth Science > Climate Indicators > Atmospheric/Ocean Indicators > Teleconnections > East Atlantic Pattern > Eatl");
        add("Earth Science > Climate Indicators > Atmospheric/Ocean Indicators > Teleconnections > Eastern Atlantic Western Russia Pattern > Eatl/Wrus");
        add("Earth Science > Climate Indicators > Atmospheric/Ocean Indicators > Teleconnections > Eastern Pacific Oscillation > Ep/Np");
        add("Earth Science > Climate Indicators > Atmospheric/Ocean Indicators > Teleconnections > El Nino Southern Oscillation (Enso) > Enso");
        add("Earth Science > Climate Indicators > Atmospheric/Ocean Indicators > Teleconnections > Madden-Julian Oscillation > Mjo");
        add("Earth Science > Climate Indicators > Atmospheric/Ocean Indicators > Teleconnections > Multivariate Enso Index > Mei");
        add("Earth Science > Climate Indicators > Atmospheric/Ocean Indicators > Teleconnections > North Atlantic Oscillation > Nao");
        add("Earth Science > Climate Indicators > Atmospheric/Ocean Indicators > Teleconnections > North Pacific Oscillation > Npo");
        add("Earth Science > Climate Indicators > Atmospheric/Ocean Indicators > Teleconnections > North Pacific Pattern > Np");
        add("Earth Science > Climate Indicators > Atmospheric/Ocean Indicators > Teleconnections > Northern Oscillation Index > Noi");
        add("Earth Science > Climate Indicators > Atmospheric/Ocean Indicators > Teleconnections > Pacific Decadal Oscillation > Pdo");
        add("Earth Science > Climate Indicators > Atmospheric/Ocean Indicators > Teleconnections > Pacific/North American (Pna) Pattern > Pna");
        add("Earth Science > Climate Indicators > Atmospheric/Ocean Indicators > Teleconnections > Pacific Transition Index > Pt");
        add("Earth Science > Climate Indicators > Atmospheric/Ocean Indicators > Teleconnections > Quasi-Biennial Oscillation > Qbo");
        add("Earth Science > Climate Indicators > Atmospheric/Ocean Indicators > Teleconnections > Southern Oscillation Index > Soi");
        add("Earth Science > Climate Indicators > Atmospheric/Ocean Indicators > Teleconnections > Tropical/Northern Hemisphere Pattern > Tnh");
        add("Earth Science > Climate Indicators > Atmospheric/Ocean Indicators > Teleconnections > West Pacific Index > Wp");
        add("Earth Science > Climate Indicators > Paleoclimate Indicators > Biological Records > Tree Rings > Isotopic Analysis");
        add("Earth Science > Climate Indicators > Paleoclimate Indicators > Biological Records > Tree Rings > Isotopic Analysis");
        add("Earth Science > Climate Indicators > Paleoclimate Indicators > Biological Records > Tree Rings > Isotopic Analysis");
        add("Earth Science > Climate Indicators > Paleoclimate Indicators > Biological Records > Tree Rings > Isotopic Analysis");
        add("Earth Science > Climate Indicators > Paleoclimate Indicators > Ice Core Records > Isotopes > Argon Isotopes");
        add("Earth Science > Climate Indicators > Paleoclimate Indicators > Ice Core Records > Isotopes > Nitrogen Isotopes");
        add("Earth Science > Climate Indicators > Paleoclimate Indicators > Ice Core Records > Isotopes > Oxygen Isotopes");
        add("Earth Science > Climate Indicators > Paleoclimate Indicators > Ice Core Records > Particulate Matter > Microparticle Concentration");
        add("Earth Science > Climate Indicators > Paleoclimate Indicators > Land Records > Fire History > Charcoal Sediment");
        add("Earth Science > Climate Indicators > Paleoclimate Indicators > Land Records > Fire History > Fire Scar Date");
        add("Earth Science > Climate Indicators > Paleoclimate Indicators > Land Records > Sediments > Sediment Thickness");
        add("Earth Science > Climate Indicators > Paleoclimate Indicators > Ocean/Lake Records > Sediments > Sediment Thickness");
        add("Earth Science > Climate Indicators > Paleoclimate Indicators > Paleoclimate Reconstructions > Sediments > Sediment Thickness");
        add("Earth Science > Cryosphere > Glaciers/Ice Sheets > Ice Sheets > Ice Sheet Measurements > Rifts");
        add("Earth Science > Human Dimensions > Public Health > Diseases/Epidemics > Epidemiology > Tele-Epidemiology");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Aeolian Landforms > Dunes > Crescentic (Barchan/Transverse) Dune");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Aeolian Landforms > Dunes > Dome Dune");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Aeolian Landforms > Dunes > Longitudinal/Linear Dune");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Aeolian Landforms > Dunes > Parabolic Dune");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Aeolian Landforms > Dunes > Star Dune");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Aeolian Processes > Abrasion > Ventifacts");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Aeolian Processes > Abrasion > Yardangs");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Aeolian Processes > Sediment Transport > Loess");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Aeolian Processes > Sediment Transport > Monadnock");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Aeolian Processes > Sedimentation > Sediment Chemistry");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Aeolian Processes > Sedimentation > Sediment Composition");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Aeolian Processes > Sedimentation > Stratigraphic Sequence");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Coastal Landforms > Coral Reefs > Apron Reef");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Coastal Landforms > Coral Reefs > Atoll Reef");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Coastal Landforms > Coral Reefs > Bank Reef");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Coastal Landforms > Coral Reefs > Barrier Reef");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Coastal Landforms > Coral Reefs > Fringing Reef");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Coastal Landforms > Coral Reefs > Patch Reef");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Coastal Landforms > Coral Reefs > Ribbon Reef");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Coastal Landforms > Coral Reefs > Table Reef");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Coastal Landforms > Dunes > Crescentic (Barchan/Transverse)");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Coastal Landforms > Dunes > Dome Dune");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Coastal Landforms > Dunes > Longitudinal/Linear Dune");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Coastal Landforms > Dunes > Parabolic Dune");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Coastal Landforms > Dunes > Star Dune");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Coastal Processes > Sedimentation > Sediment Chemistry");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Coastal Processes > Sedimentation > Sediment Composition");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Coastal Processes > Sedimentation > Stratigraphic Sequence");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Fluvial Landforms > Valley > V Shaped Valley");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Fluvial Processes > Sedimentation > Sediment Chemistry");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Fluvial Processes > Sedimentation > Sediment Composition");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Fluvial Processes > Sedimentation > Stratigraphic Sequence");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Glacial Landforms > Crevasses > Longitudinal Crevasses");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Glacial Landforms > Crevasses > Marginal Crevasses");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Glacial Landforms > Crevasses > Transverse Crevasses");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Glacial Landforms > Moraines > Lateral Moraine");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Glacial Landforms > Moraines > Medial Moraine");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Glacial Landforms > Moraines > Recessional Moraine");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Glacial Landforms > Moraines > Ribbed/Rogan Moraine");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Glacial Landforms > Moraines > Terminal Moraine");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Glacial Processes > Freeze/Thaw > Basal Ice Freezing");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Glacial Processes > Sedimentation > Sediment Chemistry");
        add("Earth Science > Land Surface > Geomorphic Landforms/Processes > Glacial Processes > Sedimentation > Stratigraphic Sequence");
        add("Earth Science > Land Surface > Land Use/Land Cover > Land Use/Land Cover Classification > Vegetation Index > Normalized Difference Vegetation Index (Ndvi)");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Aeolian Landforms > Dunes > Crescentic (Barchan/Transverse) Dune");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Aeolian Landforms > Dunes > Dome Dune");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Aeolian Landforms > Dunes > Longitudinal/Linear Dune");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Aeolian Landforms > Dunes > Parabolic Dune");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Aeolian Landforms > Dunes > Star Dune");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Aeolian Processes > Abrasion > Ventifacts");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Aeolian Processes > Abrasion > Yardangs");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Aeolian Processes > Sediment Transport > Loess");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Aeolian Processes > Sediment Transport > Monadnock");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Aeolian Processes > Sedimentation > Sediment Chemistry");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Aeolian Processes > Sedimentation > Sediment Composition");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Aeolian Processes > Sedimentation > Stratigraphic Sequence");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Coastal Landforms > Coral Reefs > Apron Reef");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Coastal Landforms > Coral Reefs > Atoll Reef");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Coastal Landforms > Coral Reefs > Bank Reef");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Coastal Landforms > Coral Reefs > Barrier Reef");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Coastal Landforms > Coral Reefs > Fringing Reef");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Coastal Landforms > Coral Reefs > Patch Reef");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Coastal Landforms > Coral Reefs > Ribbon Reef");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Coastal Landforms > Coral Reefs > Table Reef");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Coastal Landforms > Dunes > Crescentic (Barchan/Transverse) Dune");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Coastal Landforms > Dunes > Dome Dune");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Coastal Landforms > Dunes > Longitudinal/Linear Dune");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Coastal Landforms > Dunes > Parabolic Dune");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Coastal Landforms > Dunes > Star Dune");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Coastal Processes > Sedimentation > Sediment Chemistry");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Coastal Processes > Sedimentation > Sediment Composition");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Coastal Processes > Sedimentation > Straitraphic Sequence");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Coastal Processes > Wave Erosion > Degradation");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Fluvial Landforms > Valley > V Shapped Valley");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Fluvial Processes > Sedimentation > Sediment Chemistry");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Fluvial Processes > Sedimentation > Sediment Composition");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Fluvial Processes > Sedimentation > Straitigraphic Sequence");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Glacial Landforms > Crevasses > Longitudinal Crevasses");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Glacial Landforms > Crevasses > Marginal Crevasses");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Glacial Landforms > Crevasses > Transverse Crevasses");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Glacial Landforms > Moraines > Lateral Moraine");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Glacial Landforms > Moraines > Medial Moraine");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Glacial Landforms > Moraines > Recessional Moraine");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Glacial Landforms > Moraines > Ribbed/Rogan Moraine");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Glacial Landforms > Moraines > Terminal Moraine");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Glacial Processes > Freeze/Thaw > Basal Ice Freezing");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Glacial Processes > Sedimentation > Sediment Chemistry");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Glacial Processes > Sedimentation > Stratigraphic Sequence");
        add("Earth Science > Solid Earth > Geomorphic Landforms/Processes > Karst Processes > Karst Hydrology > Subsurface Drainage");
        add("Earth Science > Solid Earth > Geothermal Dynamics > Geothermal Temperature > Temperature Gradient > Temperature Gradient Rate");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Gas Hydrates > Gas Hydrates Physical/Optical Properties > Cleavage");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Gas Hydrates > Gas Hydrates Physical/Optical Properties > Color");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Gas Hydrates > Gas Hydrates Physical/Optical Properties > Composition/Texture");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Gas Hydrates > Gas Hydrates Physical/Optical Properties > Electrical");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Gas Hydrates > Gas Hydrates Physical/Optical Properties > Hardness");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Gas Hydrates > Gas Hydrates Physical/Optical Properties > Luminescence");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Gas Hydrates > Gas Hydrates Physical/Optical Properties > Luster");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Gas Hydrates > Gas Hydrates Physical/Optical Properties > Reflection");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Gas Hydrates > Gas Hydrates Physical/Optical Properties > Specific Gravity");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Gas Hydrates > Gas Hydrates Physical/Optical Properties > Stability");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Igneous Rocks > Igneous Rock Physical/Optical Properties > Cleavage");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Igneous Rocks > Igneous Rock Physical/Optical Properties > Color");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Igneous Rocks > Igneous Rock Physical/Optical Properties > Composition/Texture");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Igneous Rocks > Igneous Rock Physical/Optical Properties > Electrical");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Igneous Rocks > Igneous Rock Physical/Optical Properties > Hardness");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Igneous Rocks > Igneous Rock Physical/Optical Properties > Luminescence");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Igneous Rocks > Igneous Rock Physical/Optical Properties > Luster");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Igneous Rocks > Igneous Rock Physical/Optical Properties > Reflection");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Igneous Rocks > Igneous Rock Physical/Optical Properties > Specific Gravity");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Igneous Rocks > Igneous Rock Physical/Optical Properties > Stability");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Metals > Metals Physical/Optical Properties > Cleavage");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Metals > Metals Physical/Optical Properties > Color");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Metals > Metals Physical/Optical Properties > Composition/Structure");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Metals > Metals Physical/Optical Properties > Electrical");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Metals > Metals Physical/Optical Properties > Hardness");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Metals > Metals Physical/Optical Properties > Luminescence");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Metals > Metals Physical/Optical Properties > Luster");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Metals > Metals Physical/Optical Properties > Reflection");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Metals > Metals Physical/Optical Properties > Specific Gravity");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Metals > Metals Physical/Optical Properties > Stability");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Metamorphic Rocks > Metamorphic Rock Physical/Optical Properties > Cleavage");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Metamorphic Rocks > Metamorphic Rock Physical/Optical Properties > Color");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Metamorphic Rocks > Metamorphic Rock Physical/Optical Properties > Composition/Texture");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Metamorphic Rocks > Metamorphic Rock Physical/Optical Properties > Electricial");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Metamorphic Rocks > Metamorphic Rock Physical/Optical Properties > Hardness");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Metamorphic Rocks > Metamorphic Rock Physical/Optical Properties > Luminescence");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Metamorphic Rocks > Metamorphic Rock Physical/Optical Properties > Luster");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Metamorphic Rocks > Metamorphic Rock Physical/Optical Properties > Reflection");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Metamorphic Rocks > Metamorphic Rock Physical/Optical Properties > Specific Gravity");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Metamorphic Rocks > Metamorphic Rock Physical/Optical Properties > Stability");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Meteorites > Meteorite Physical/Optical Properties > Cleavage");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Meteorites > Meteorite Physical/Optical Properties > Color");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Meteorites > Meteorite Physical/Optical Properties > Composition/Structure");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Meteorites > Meteorite Physical/Optical Properties > Electrical");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Meteorites > Meteorite Physical/Optical Properties > Hardness");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Meteorites > Meteorite Physical/Optical Properties > Luminescence");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Meteorites > Meteorite Physical/Optical Properties > Luster");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Meteorites > Meteorite Physical/Optical Properties > Reflection");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Meteorites > Meteorite Physical/Optical Properties > Specific Gravity");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Meteorites > Meteorite Physical/Optical Properties > Stability");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Meteorites > Meteorite Vertical/Geogrpahic Distribution > Luster");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Minerals > Mineral Physical/Optical Properties > Cleavage");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Minerals > Mineral Physical/Optical Properties > Color");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Minerals > Mineral Physical/Optical Properties > Composition/Texture");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Minerals > Mineral Physical/Optical Properties > Electrical");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Minerals > Mineral Physical/Optical Properties > Hardness");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Minerals > Mineral Physical/Optical Properties > Luminescence");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Minerals > Mineral Physical/Optical Properties > Luster");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Minerals > Mineral Physical/Optical Properties > Reflection");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Minerals > Mineral Physical/Optical Properties > Specific Gravity");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Minerals > Mineral Physical/Optical Properties > Stability");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Non-Metallic Minerals > Non-Metallic Mineral Physical/Optical Properties > Cleavage");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Non-Metallic Minerals > Non-Metallic Mineral Physical/Optical Properties > Color");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Non-Metallic Minerals > Non-Metallic Mineral Physical/Optical Properties > Composition/Texture");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Non-Metallic Minerals > Non-Metallic Mineral Physical/Optical Properties > Electrical");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Non-Metallic Minerals > Non-Metallic Mineral Physical/Optical Properties > Hardness");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Non-Metallic Minerals > Non-Metallic Mineral Physical/Optical Properties > Luminescence");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Non-Metallic Minerals > Non-Metallic Mineral Physical/Optical Properties > Luster");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Non-Metallic Minerals > Non-Metallic Mineral Physical/Optical Properties > Reflection");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Non-Metallic Minerals > Non-Metallic Mineral Physical/Optical Properties > Specific Gravity");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Non-Metallic Minerals > Non-Metallic Mineral Physical/Optical Properties > Stability");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Sedimentary Rocks > Sedimentary Rock Physical/Optical Properties > Cleavage");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Sedimentary Rocks > Sedimentary Rock Physical/Optical Properties > Color");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Sedimentary Rocks > Sedimentary Rock Physical/Optical Properties > Composition/Texture");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Sedimentary Rocks > Sedimentary Rock Physical/Optical Properties > Electrical");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Sedimentary Rocks > Sedimentary Rock Physical/Optical Properties > Hardness");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Sedimentary Rocks > Sedimentary Rock Physical/Optical Properties > Luminescence");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Sedimentary Rocks > Sedimentary Rock Physical/Optical Properties > Luster");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Sedimentary Rocks > Sedimentary Rock Physical/Optical Properties > Reflection");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Sedimentary Rocks > Sedimentary Rock Physical/Optical Properties > Specific Gravity");
        add("Earth Science > Solid Earth > Rocks/Minerals/Crystals > Sedimentary Rocks > Sedimentary Rock Physical/Optical Properties > Stability");
        add("Earth Science > Solid Earth > Tectonics > Earthquakes > Seismic Profile > Seismic Body Waves");
        add("Earth Science > Solid Earth > Tectonics > Earthquakes > Seismic Profile > Seismic Surface Waves");
        add("Earth Science > Solid Earth > Tectonics > Plate Tectonics > Crustal Motion > Crustal Motion Direction");
        add("Earth Science > Solid Earth > Tectonics > Plate Tectonics > Crustal Motion > Crustal Motion Rate");
        add("Earth Science > Solid Earth > Tectonics > Plate Tectonics > Fault Movement > Fault Movement Direction");
        add("Earth Science > Solid Earth > Tectonics > Plate Tectonics > Fault Movement > Fault Movement Rate");
        add("Earth Science > Solid Earth > Tectonics > Plate Tectonics > Isostatic Rebound > Rebound Direction");
        add("Earth Science > Solid Earth > Tectonics > Plate Tectonics > Isostatic Rebound > Rebound Rate");
        add("Earth Science > Solid Earth > Tectonics > Plate Tectonics > Lithospheric Plate Motion > Plate Motion Direction");
        add("Earth Science > Solid Earth > Tectonics > Plate Tectonics > Lithospheric Plate Motion > Plate Motion Rate");
        add("Earth Science > Solid Earth > Tectonics > Volcanic Activity > Eruption Dynamics > Ash/Dust Composition");
        add("Earth Science > Solid Earth > Tectonics > Volcanic Activity > Eruption Dynamics > Ash/Dust Dispersion");
        add("Earth Science > Solid Earth > Tectonics > Volcanic Activity > Eruption Dynamics > Gas/Aerosol Composition");
        add("Earth Science > Solid Earth > Tectonics > Volcanic Activity > Eruption Dynamics > Gas/Aerosol Dispersion");
        add("Earth Science > Solid Earth > Tectonics > Volcanic Activity > Eruption Dynamics > Lava Composition/Texture");
        add("Earth Science > Solid Earth > Tectonics > Volcanic Activity > Eruption Dynamics > Lava Speed/Flow");
        add("Earth Science > Solid Earth > Tectonics > Volcanic Activity > Eruption Dynamics > Magma Composition/Texture");
        add("Earth Science > Solid Earth > Tectonics > Volcanic Activity > Eruption Dynamics > Magma Speed/Flow");
        add("Earth Science > Solid Earth > Tectonics > Volcanic Activity > Eruption Dynamics > Pyroclastic Partical Size Distribution");
        add("Earth Science > Solid Earth > Tectonics > Volcanic Activity > Eruption Dynamics > Pyroclastics Composition/Texture");
        add("Earth Science > Solid Earth > Tectonics > Volcanic Activity > Eruption Dynamics > Volcanic Explosivity");
        add("Earth Science > Solid Earth > Tectonics > Volcanic Activity > Eruption Dynamics > Volcanic Gases");
        add("Earth Science > Terrestrial Hydrosphere > Ground Water > Ground Water Features > Water Table > Water Table Depth");
        add("Earth Science > Terrestrial Hydrosphere > Ground Water > Ground Water Processes/Measurements > Aquifer Recharge > Aquifer Depth");
        add("Earth Science > Terrestrial Hydrosphere > Ground Water > Ground Water Processes/Measurements > Aquifer Recharge > Recharge Amount");
        add("Earth Science > Terrestrial Hydrosphere > Ground Water > Ground Water Processes/Measurements > Aquifer Recharge > Recharge Frequency");
        add("Earth Science > Terrestrial Hydrosphere > Ground Water > Ground Water Processes/Measurements > Discharge > Discharge Amount");
        add("Earth Science > Terrestrial Hydrosphere > Ground Water > Ground Water Processes/Measurements > Discharge > Discharge Rate");
        add("Earth Science > Terrestrial Hydrosphere > Ground Water > Ground Water Processes/Measurements > Dispersion > Dispersion Frequency");
        add("Earth Science > Terrestrial Hydrosphere > Ground Water > Ground Water Processes/Measurements > Dispersion > Dispersion Rate");
        add("Earth Science > Terrestrial Hydrosphere > Ground Water > Ground Water Processes/Measurements > Drainage > Drainage Amount");
        add("Earth Science > Terrestrial Hydrosphere > Ground Water > Ground Water Processes/Measurements > Drainage > Drainage Direction");
        add("Earth Science > Terrestrial Hydrosphere > Ground Water > Ground Water Processes/Measurements > Infiltration > Infiltration Amount");
        add("Earth Science > Terrestrial Hydrosphere > Ground Water > Ground Water Processes/Measurements > Infiltration > Infiltration Frequency");
        add("Earth Science > Terrestrial Hydrosphere > Ground Water > Ground Water Processes/Measurements > Infiltration > Infiltration Rate");
        add("Earth Science > Terrestrial Hydrosphere > Ground Water > Ground Water Processes/Measurements > Land Subsidence > Subsidence Amount");
        add("Earth Science > Terrestrial Hydrosphere > Ground Water > Ground Water Processes/Measurements > Land Subsidence > Subsidence Rate");
        add("Earth Science > Terrestrial Hydrosphere > Ground Water > Ground Water Processes/Measurements > Percolation > Percolation Amount");
        add("Earth Science > Terrestrial Hydrosphere > Ground Water > Ground Water Processes/Measurements > Percolation > Percolation Rate");
        add("Earth Science > Terrestrial Hydrosphere > Ground Water > Ground Water Processes/Measurements > Saltwater Intrusion > Intrusion Amount");
        add("Earth Science > Terrestrial Hydrosphere > Ground Water > Ground Water Processes/Measurements > Saltwater Intrusion > Intrusion Rate");
        add("Earth Science > Terrestrial Hydrosphere > Ground Water > Ground Water Processes/Measurements > Subsurface Flow > Average Flow");
        add("Earth Science > Terrestrial Hydrosphere > Ground Water > Ground Water Processes/Measurements > Subsurface Flow > Flow Velocity");
        add("Earth Science > Terrestrial Hydrosphere > Ground Water > Ground Water Processes/Measurements > Subsurface Flow > Peak Flow");
        add("Earth Science > Terrestrial Hydrosphere > Surface Water > Surface Water Processes/Measurements > Aquifer Recharge > Aquifer Depth");
        add("Earth Science > Terrestrial Hydrosphere > Surface Water > Surface Water Processes/Measurements > Aquifer Recharge > Recharge Amount");
        add("Earth Science > Terrestrial Hydrosphere > Surface Water > Surface Water Processes/Measurements > Aquifer Recharge > Recharge Frequency");
        add("Earth Science > Terrestrial Hydrosphere > Surface Water > Surface Water Processes/Measurements > Discharge/Flow > Average Flow");
        add("Earth Science > Terrestrial Hydrosphere > Surface Water > Surface Water Processes/Measurements > Discharge/Flow > Base Flow");
        add("Earth Science > Terrestrial Hydrosphere > Surface Water > Surface Water Processes/Measurements > Discharge/Flow > Flow Velocity");
        add("Earth Science > Terrestrial Hydrosphere > Surface Water > Surface Water Processes/Measurements > Discharge/Flow > Peak Flow");
        add("Earth Science > Terrestrial Hydrosphere > Surface Water > Surface Water Processes/Measurements > Drainage > Drainage Amount");
        add("Earth Science > Terrestrial Hydrosphere > Surface Water > Surface Water Processes/Measurements > Drainage > Drainage Direction");
        add("Earth Science > Terrestrial Hydrosphere > Surface Water > Surface Water Processes/Measurements > Floods > Flood Frequency");
        add("Earth Science > Terrestrial Hydrosphere > Surface Water > Surface Water Processes/Measurements > Floods > Flood Levels");
        add("Earth Science > Terrestrial Hydrosphere > Surface Water > Surface Water Processes/Measurements > Inundation > Inundation Amount");
        add("Earth Science > Terrestrial Hydrosphere > Surface Water > Surface Water Processes/Measurements > Inundation > Inundation Frequency");
        add("Earth Science > Terrestrial Hydrosphere > Surface Water > Surface Water Processes/Measurements > Inundation > Inundation Level");
        add("Earth Science > Terrestrial Hydrosphere > Surface Water > Surface Water Processes/Measurements > Runoff > Runoff Rate");
        add("Earth Science > Terrestrial Hydrosphere > Surface Water > Surface Water Processes/Measurements > Runoff > Total Runoff");
    }
}
