server:
    port: 8383
    contextPath: /oap
---
grails:
    profile: web
    codegen:
        defaultPackage: oap
    spring:
        transactionManagement:
            proxies: false
    controllers:
        upload:
            maxFileSize: 154800000
            maxRequestSize: 154800000
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
    http:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    resources:
        pattern: '/**'
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password:

# ./gradlew -Dgrails.env=[environment] assemble
environments:
    sa_oa_create_3306:
        dataSource:
            dbCreate: create
            url: jdbc:mysql://localhost:3306/oapme?useUnicode=true&characterEncoding=UTF-8
            driverClassName: "com.mysql.cj.jdbc.Driver"
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            username: oapweb
            password: webster
#            logSql: true
#            formatSql: true
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

    buckeye_oa_preserve:
        dataSource:
            dbCreate: validate
            url: jdbc:mysql://localhost:63306/ioap_me?useUnicode=true&characterEncoding=UTF-8
            driverClassName: "com.mysql.cj.jdbc.Driver"
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            username: scientist
            password: qc4socat3
#            logSql: true
#            formatSql: true
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

    buckeye_oa_create:
        dataSource:
            dbCreate: create
            url: jdbc:mysql://localhost:63306/ioap_me?useUnicode=true&characterEncoding=UTF-8
            driverClassName: "com.mysql.cj.jdbc.Driver"
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            username: scientist
            password: qc4socat3
#            logSql: false
#            formatSql: false
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
    sour_oa_create:
        dataSource:
            dbCreate: create
            url: jdbc:mysql://localhost:3306/ioap_me?useUnicode=true&characterEncoding=UTF-8
            driverClassName: "com.mysql.cj.jdbc.Driver"
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            username: scientist
            password: qc4socat3
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
    oapme_devexp:
        dataSource:
            dbCreate: create
            url: jdbc:mysql://localhost:3306/oapme_devexp?useUnicode=true&characterEncoding=UTF-8
            driverClassName: "com.mysql.cj.jdbc.Driver"
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            username: scientist
            password: qc4socat3
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
    devo:
        dataSource:
            dbCreate: create-drop
            url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    procreate:
        dataSource:
            dbCreate: create
            url: jdbc:mysql://localhost:3306/ioap_me?useUnicode=true&characterEncoding=UTF-8
            driverClassName: "com.mysql.cj.jdbc.Driver"
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            username: scientist
            password: qc4socat3
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
    production:
        dataSource:
            dbCreate: create
            url: jdbc:mysql://localhost:3306/ioap_me?useUnicode=true&characterEncoding=UTF-8
            driverClassName: "com.mysql.cj.jdbc.Driver"
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            username: scientist
            password: qc4socat3
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
    protest:
        dataSource:
            dbCreate: create
            url: jdbc:mysql://localhost:3306/ioap_test?useUnicode=true&characterEncoding=UTF-8
            driverClassName: "com.mysql.cj.jdbc.Driver"
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            username: scientist
            password: qc4socat3
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
    standalone_production:
        dataSource:
            dbCreate: create
            url: jdbc:mysql://localhost:3306/oapme?useUnicode=true&characterEncoding=UTF-8
            driverClassName: "com.mysql.cj.jdbc.Driver"
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            username: scientist
            password: qc4socat3
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
